### ISSUE TITLE
Space at top for dragging window

### ISSUE THREAD

**Issue by Chemiseblanc** [lr-tech/OnelineProton#3]
This may be specific to Firefox on Windows, but I've found that when the tab bar is full there isn't anywhere at the top to drag the window in order to move it, or to quickly switch between fullscreen and windowed modes.

Adding a small margin at the top of the window would fix this. I've found something like
```css
:root[sizemode="maximized"] #TabsToolbar {
  margin-top: 1px;
}

#TabsToolbar {
  margin-top: 5px;
}
```
provides enough space so that finding the drag-able area isn't difficult in windowed mode and takes up minimal space while still being functional when fullscreen.
